name: Get tag name

on:
 workflow_dispatch

jobs:
 show-name:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: show name
    run: |
        git tag
        git log
        echo "git not working"
        
  
